//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceFileNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceFileNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundSystem.Resources.SourceFileNames", typeof(SourceFileNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArrowOff1.wav.
        /// </summary>
        internal static string arrowOff1 {
            get {
                return ResourceManager.GetString("arrowOff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArrowOff2.wav.
        /// </summary>
        internal static string arrowOff2 {
            get {
                return ResourceManager.GetString("arrowOff2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssassinCought.wav.
        /// </summary>
        internal static string assassinCought {
            get {
                return ResourceManager.GetString("assassinCought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssassinJah.wav.
        /// </summary>
        internal static string assassinJah {
            get {
                return ResourceManager.GetString("assassinJah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssassinJhuee.wav.
        /// </summary>
        internal static string assassinJhuee {
            get {
                return ResourceManager.GetString("assassinJhuee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssassinJooaah.wav.
        /// </summary>
        internal static string assassinJooaah {
            get {
                return ResourceManager.GetString("assassinJooaah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssassinLongDeath.wav.
        /// </summary>
        internal static string assassinLongDeath {
            get {
                return ResourceManager.GetString("assassinLongDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssassinOhm.wav.
        /// </summary>
        internal static string assassinOhm {
            get {
                return ResourceManager.GetString("assassinOhm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssassinScream1.wav.
        /// </summary>
        internal static string assassinScream1 {
            get {
                return ResourceManager.GetString("assassinScream1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssassinScream2.wav.
        /// </summary>
        internal static string assassinScream2 {
            get {
                return ResourceManager.GetString("assassinScream2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssassinShortDeath.wav.
        /// </summary>
        internal static string assassinShortDeath {
            get {
                return ResourceManager.GetString("assassinShortDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssassinYeam.wav.
        /// </summary>
        internal static string assassinYeam {
            get {
                return ResourceManager.GetString("assassinYeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossbowOff.wav.
        /// </summary>
        internal static string crossbowOff {
            get {
                return ResourceManager.GetString("crossbowOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaggerFight1.wav.
        /// </summary>
        internal static string daggerFight1 {
            get {
                return ResourceManager.GetString("daggerFight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaggerFight2.wav.
        /// </summary>
        internal static string daggerFight2 {
            get {
                return ResourceManager.GetString("daggerFight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaggerFight3.wav.
        /// </summary>
        internal static string daggerFight3 {
            get {
                return ResourceManager.GetString("daggerFight3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaggerFight4.wav.
        /// </summary>
        internal static string daggerFight4 {
            get {
                return ResourceManager.GetString("daggerFight4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaggerFight5.wav.
        /// </summary>
        internal static string daggerFight5 {
            get {
                return ResourceManager.GetString("daggerFight5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat.wav.
        /// </summary>
        internal static string defeat {
            get {
                return ResourceManager.GetString("defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastleButcher.mp3.
        /// </summary>
        internal static string endingMusic {
            get {
                return ResourceManager.GetString("endingMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explode.wav.
        /// </summary>
        internal static string explode {
            get {
                return ResourceManager.GetString("explode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fanfare1.wav.
        /// </summary>
        internal static string fanfare1 {
            get {
                return ResourceManager.GetString("fanfare1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fanfare2.wav.
        /// </summary>
        internal static string fanfare2 {
            get {
                return ResourceManager.GetString("fanfare2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fanfare3.wav.
        /// </summary>
        internal static string fanfare3 {
            get {
                return ResourceManager.GetString("fanfare3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fanfare4.wav.
        /// </summary>
        internal static string fanfare4 {
            get {
                return ResourceManager.GetString("fanfare4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnightAaa.wav.
        /// </summary>
        internal static string knightAaa {
            get {
                return ResourceManager.GetString("knightAaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnightHou.wav.
        /// </summary>
        internal static string knightHou {
            get {
                return ResourceManager.GetString("knightHou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnightHouu.wav.
        /// </summary>
        internal static string knightHouu {
            get {
                return ResourceManager.GetString("knightHouu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnightHruuhb.wav.
        /// </summary>
        internal static string knightHruuhb {
            get {
                return ResourceManager.GetString("knightHruuhb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnightLongDeath.wav.
        /// </summary>
        internal static string knightLongDeath {
            get {
                return ResourceManager.GetString("knightLongDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnightNey.wav.
        /// </summary>
        internal static string knightNey {
            get {
                return ResourceManager.GetString("knightNey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnightScream1.wav.
        /// </summary>
        internal static string knightScream1 {
            get {
                return ResourceManager.GetString("knightScream1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnightScream2.wav.
        /// </summary>
        internal static string knightScream2 {
            get {
                return ResourceManager.GetString("knightScream2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnightShortDeath.wav.
        /// </summary>
        internal static string knightShortDeath {
            get {
                return ResourceManager.GetString("knightShortDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnightUhraa.wav.
        /// </summary>
        internal static string knightUhraa {
            get {
                return ResourceManager.GetString("knightUhraa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KnightUueh.wav.
        /// </summary>
        internal static string knightUueh {
            get {
                return ResourceManager.GetString("knightUueh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManShotByArrow.wav.
        /// </summary>
        internal static string manShotByArrow {
            get {
                return ResourceManager.GetString("manShotByArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManShotByCrossbow.wav.
        /// </summary>
        internal static string manShotByCrossbow {
            get {
                return ResourceManager.GetString("manShotByCrossbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextCastle.mp3.
        /// </summary>
        internal static string menuMusic {
            get {
                return ResourceManager.GetString("menuMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to round1Music.mp3.
        /// </summary>
        internal static string round1Music {
            get {
                return ResourceManager.GetString("round1Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to round2Music.mp3.
        /// </summary>
        internal static string round2Music {
            get {
                return ResourceManager.GetString("round2Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShotByArrow.wav.
        /// </summary>
        internal static string shotByArrow {
            get {
                return ResourceManager.GetString("shotByArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShotByCrossbow.wav.
        /// </summary>
        internal static string shotByCrossbow {
            get {
                return ResourceManager.GetString("shotByCrossbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepsGrass1.wav.
        /// </summary>
        internal static string stepsGrass1 {
            get {
                return ResourceManager.GetString("stepsGrass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepsGrass2.wav.
        /// </summary>
        internal static string stepsGrass2 {
            get {
                return ResourceManager.GetString("stepsGrass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepsInside1.wav.
        /// </summary>
        internal static string stepsInside1 {
            get {
                return ResourceManager.GetString("stepsInside1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepsInside2.wav.
        /// </summary>
        internal static string stepsInside2 {
            get {
                return ResourceManager.GetString("stepsInside2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepsInside3.wav.
        /// </summary>
        internal static string stepsInside3 {
            get {
                return ResourceManager.GetString("stepsInside3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepsPath1.wav.
        /// </summary>
        internal static string stepsPath1 {
            get {
                return ResourceManager.GetString("stepsPath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepsPath2.wav.
        /// </summary>
        internal static string stepsPath2 {
            get {
                return ResourceManager.GetString("stepsPath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepsSlower.wav.
        /// </summary>
        internal static string stepsSlower {
            get {
                return ResourceManager.GetString("stepsSlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepsStairs.wav.
        /// </summary>
        internal static string stepsStairs {
            get {
                return ResourceManager.GetString("stepsStairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StepsStone.wav.
        /// </summary>
        internal static string stepsStone {
            get {
                return ResourceManager.GetString("stepsStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwordFight1.wav.
        /// </summary>
        internal static string swordFight1 {
            get {
                return ResourceManager.GetString("swordFight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwordFight2.wav.
        /// </summary>
        internal static string swordFight2 {
            get {
                return ResourceManager.GetString("swordFight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwordFight3.wav.
        /// </summary>
        internal static string swordFight3 {
            get {
                return ResourceManager.GetString("swordFight3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwordFight4.wav.
        /// </summary>
        internal static string swordFight4 {
            get {
                return ResourceManager.GetString("swordFight4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwordFight5.wav.
        /// </summary>
        internal static string swordFight5 {
            get {
                return ResourceManager.GetString("swordFight5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastleButcher.mp3.
        /// </summary>
        internal static string welcomeMusic {
            get {
                return ResourceManager.GetString("welcomeMusic", resourceCulture);
            }
        }
    }
}
