//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleButcher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class KeyMapping : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeyMapping defaultInstance = ((KeyMapping)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeyMapping())));
        
        public static KeyMapping Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public global::System.Windows.Forms.Keys ToggleFullscreen {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ToggleFullscreen"]));
            }
            set {
                this["ToggleFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.Windows.Forms.Keys Forward {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Forward"]));
            }
            set {
                this["Forward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys Backward {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Backward"]));
            }
            set {
                this["Backward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::System.Windows.Forms.Keys StrafeLeft {
            get {
                return ((global::System.Windows.Forms.Keys)(this["StrafeLeft"]));
            }
            set {
                this["StrafeLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::System.Windows.Forms.Keys StrafeRight {
            get {
                return ((global::System.Windows.Forms.Keys)(this["StrafeRight"]));
            }
            set {
                this["StrafeRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::System.Windows.Forms.Keys Jump {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Jump"]));
            }
            set {
                this["Jump"] = value;
            }
        }
    }
}
