//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceShooter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class KeyMapping : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeyMapping defaultInstance = ((KeyMapping)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeyMapping())));
        
        public static KeyMapping Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public global::System.Windows.Forms.Keys ToggleFullscreen {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ToggleFullscreen"]));
            }
            set {
                this["ToggleFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tab")]
        public global::System.Windows.Forms.Keys FullSpeed {
            get {
                return ((global::System.Windows.Forms.Keys)(this["FullSpeed"]));
            }
            set {
                this["FullSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Back")]
        public global::System.Windows.Forms.Keys Brake {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Brake"]));
            }
            set {
                this["Brake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public global::System.Windows.Forms.Keys RollCW {
            get {
                return ((global::System.Windows.Forms.Keys)(this["RollCW"]));
            }
            set {
                this["RollCW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public global::System.Windows.Forms.Keys RollCCW {
            get {
                return ((global::System.Windows.Forms.Keys)(this["RollCCW"]));
            }
            set {
                this["RollCCW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oem6")]
        public global::System.Windows.Forms.Keys Accelerate {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Accelerate"]));
            }
            set {
                this["Accelerate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OemOpenBrackets")]
        public global::System.Windows.Forms.Keys Decellerate {
            get {
                return ((global::System.Windows.Forms.Keys)(this["Decellerate"]));
            }
            set {
                this["Decellerate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::System.Windows.Forms.Keys StrafeLeft {
            get {
                return ((global::System.Windows.Forms.Keys)(this["StrafeLeft"]));
            }
            set {
                this["StrafeLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::System.Windows.Forms.Keys StrafeRight {
            get {
                return ((global::System.Windows.Forms.Keys)(this["StrafeRight"]));
            }
            set {
                this["StrafeRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.Windows.Forms.Keys StrafeUp {
            get {
                return ((global::System.Windows.Forms.Keys)(this["StrafeUp"]));
            }
            set {
                this["StrafeUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys StrafeDown {
            get {
                return ((global::System.Windows.Forms.Keys)(this["StrafeDown"]));
            }
            set {
                this["StrafeDown"] = value;
            }
        }
    }
}
